# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelley" do
  version "0.991.971170046"

  on_macos do
    on_intel do
      sha256 "9a40d339b7f324a968f7b27b0a15a981e971dc1651d57ce695326ba036dad669"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_amd64"
      binary "shelley_darwin_amd64", target: "shelley"
    end
    on_arm do
      sha256 "81f7ddf7d5ad9d67c2e72bd34603f5f99ef9a9bcd089f4e883a2c3b1ec9437a3"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_arm64"
      binary "shelley_darwin_arm64", target: "shelley"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c2524005b591d21231e1b39a99553cb28c6273f5d75b13131966e5da52a298a"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_amd64"
      binary "shelley_linux_amd64", target: "shelley"
    end
    on_arm do
      sha256 "70b4db1a3870e028ba653f04b65889b3abd90c5550ef41d9f57048aa156cb75b"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_arm64"
      binary "shelley_linux_arm64", target: "shelley"
    end
  end

  name "shelley"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/boldsoftware/shelley"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required

end
