# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelley" do
  version "0.1084.942600042"

  on_macos do
    on_arm do
      sha256 "a60ae7d0cbb0269b8b4e88fe1d178b29341d7fa09869de3c602d15fd4dbf2b43"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_arm64"
      binary "shelley_darwin_arm64", target: "shelley"
    end
    on_intel do
      sha256 "30b6e3f02d2fbe58419ae0240570afbb949cea384e6957cd1acab8681dc7c858"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_amd64"
      binary "shelley_darwin_amd64", target: "shelley"
    end
  end
  on_linux do
    on_arm do
      sha256 "5617711d51649ecf09b1b68a24276a55deaa62437066ae204f5daa4035e35458"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_arm64"
      binary "shelley_linux_arm64", target: "shelley"
    end
    on_intel do
      sha256 "b1521d4e21a79930bb4aff37c58a2cfc8c687e1dcfe48e30463325edabf7d7e4"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_amd64"
      binary "shelley_linux_amd64", target: "shelley"
    end
  end

  name "shelley"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/boldsoftware/shelley"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
