# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelley" do
  version "0.1165.961354576"

  on_macos do
    on_arm do
      sha256 "ef68ba7bc6760666ae6fc7a60319c72424b6a20306872c1761523b60f1504980"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_arm64"
      binary "shelley_darwin_arm64", target: "shelley"
    end
    on_intel do
      sha256 "e72e0d0992aeb96a7d5369879ba16296f73c2fc0b512db7eb8f02a9a077ba081"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_darwin_amd64"
      binary "shelley_darwin_amd64", target: "shelley"
    end
  end
  on_linux do
    on_arm do
      sha256 "90330ee5f62c348d610f74a082c502f4bcfc90356d1afd0c47de857210b1bc98"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_arm64"
      binary "shelley_linux_arm64", target: "shelley"
    end
    on_intel do
      sha256 "5b20ff703127c3116493c2ebb49cb9966a0acb614c7809408bc601e6e08c3579"
      url "https://github.com/boldsoftware/shelley/releases/download/v#{version}/shelley_linux_amd64"
      binary "shelley_linux_amd64", target: "shelley"
    end
  end

  name "shelley"
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/boldsoftware/shelley"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
