# This file was generated by GoReleaser. DO NOT EDIT.
cask "shoulder" do
  version "0.10.917757031"

  on_macos do
    on_arm do
      sha256 "e6117632be47dd87106f54e122b0e2d2e6b79fba1de8cefabca455a52c3428bc"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_darwin_arm64"
      binary "shoulder_darwin_arm64", target: "shoulder"
    end
    on_intel do
      sha256 "9e5e920dc1a3e638f1cabae0792182e684bcf6b4bbe5eeb4a07186feb164dd5d"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_darwin_amd64"
      binary "shoulder_darwin_amd64", target: "shoulder"
    end
  end
  on_linux do
    on_arm do
      sha256 "872c0243346fc85c2706bdb49d25f49ee911b1224b1155867fbaeacfa9157e4e"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_linux_arm64"
      binary "shoulder_linux_arm64", target: "shoulder"
    end
    on_intel do
      sha256 "1b034c0c51a559cd5f3a85f7118c0e95335f76d774f0f77c1d4dac97a389ee13"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_linux_amd64"
      binary "shoulder_linux_amd64", target: "shoulder"
    end
  end

  name "shoulder"
  desc "Share a terminal session with an agent"
  homepage "https://github.com/boldsoftware/shoulder"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
