# This file was generated by GoReleaser. DO NOT EDIT.
cask "shoulder" do
  version "0.11.911536753"

  on_macos do
    on_arm do
      sha256 "e1a8bba4c64d3066d37452e43a65731129efb6ff7122229ec1ed2d44038a1f39"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_darwin_arm64"
      binary "shoulder_darwin_arm64", target: "shoulder"
    end
    on_intel do
      sha256 "48da807e384b05118121f57419b09a69430ea63db7e1a6f0bb6adeeef18b288e"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_darwin_amd64"
      binary "shoulder_darwin_amd64", target: "shoulder"
    end
  end
  on_linux do
    on_arm do
      sha256 "ed872a339fddee1afbdeb6cb1a501426284b597091ad95f3ff14273120d87c5d"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_linux_arm64"
      binary "shoulder_linux_arm64", target: "shoulder"
    end
    on_intel do
      sha256 "164bc094b661f45ee7d01dcd9363ce094c0eceb2b6315fd2c3f314865604124f"
      url "https://github.com/boldsoftware/shoulder/releases/download/v#{version}/shoulder_linux_amd64"
      binary "shoulder_linux_amd64", target: "shoulder"
    end
  end

  name "shoulder"
  desc "Share a terminal session with an agent"
  homepage "https://github.com/boldsoftware/shoulder"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
  end

  # No zap stanza required
end
