# This file was generated by GoReleaser. DO NOT EDIT.
cask "sketch" do
  desc "Sketch is an agentic coding tool. It draws the 🦉"
  homepage "https://sketch.dev"
  version "0.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sketch"

  on_macos do
    on_intel do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.18/sketch_0.0.18_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "13e93f850360b90e1ba99ac81cabbf18302cbd6740dd88ff35f37256164a415c"
    end
    on_arm do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.18/sketch_0.0.18_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "f1dec8cacf44db3b21c73633f1182121efd2e8377410deb700c98ad1c0bd491a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.18/sketch_0.0.18_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "2d822c502eb48c4e4c7aa662b4384f96be7c826c07d0921cbd8f23adb67a1600"
    end
    on_arm do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.18/sketch_0.0.18_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "3c8b34d49cc646f91343d851166dc62a1baad060be65aea77fd03a700b978e06"
    end
  end

  # No zap stanza required
end
