# This file was generated by GoReleaser. DO NOT EDIT.
cask "sketch" do
  desc "Sketch is an agentic coding tool. It draws the 🦉"
  homepage "https://sketch.dev"
  version "0.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sketch"

  on_macos do
    on_intel do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.20/sketch_0.0.20_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "4a5ba2e9c3ea47b2545001b23cb238c66a16d02bc5d1b2e4f74a9d4b04e6755b"
    end
    on_arm do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.20/sketch_0.0.20_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "d7ce898ff85229954287656cf4f143665f3fdc36c22e1ab21340461356b5b250"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.20/sketch_0.0.20_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "e6090bf912aa5400933d1826d58fabfaae6f11d650ff44dc5d691a4d57e32194"
    end
    on_arm do
      url "https://github.com/boldsoftware/sketch/releases/download/v0.0.20/sketch_0.0.20_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
      sha256 "bb0139f8d30cf4053f63635a51078844e95ed93d2b0289479f2fdbf990efa8d5"
    end
  end

  # No zap stanza required
end
