# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelley < Formula
  desc "A mobile-friendly, web-based, multi-modal coding agent"
  homepage "https://github.com/boldsoftware/shelley"
  version "0.32.925600652"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boldsoftware/shelley/releases/download/v0.32.925600652/shelley_darwin_amd64"
      sha256 "9394bb77b5da6d77b0f574fd2314e1267cfecd902c74da1ebc23fcf381415e83"

      def install
        bin.install "shelley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boldsoftware/shelley/releases/download/v0.32.925600652/shelley_darwin_arm64"
      sha256 "d0b6ad5ac529f346aac9d1bab19bf0a2a9d222069f310b68b0e458169ad17ee3"

      def install
        bin.install "shelley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boldsoftware/shelley/releases/download/v0.32.925600652/shelley_linux_amd64"
      sha256 "c1b820804cfb1a6ac29b51e4ab85e8364a6bd5d4266be1e171fff71474d3c866"
      def install
        bin.install "shelley"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boldsoftware/shelley/releases/download/v0.32.925600652/shelley_linux_arm64"
      sha256 "bddf93bc354f01a0cec5be3eb2e31bf5f32f1a70e8984e5bf1af07eca6f8e3f7"
      def install
        bin.install "shelley"
      end
    end
  end

  test do
    system "#{bin}/shelley", "--help"
  end
end
